Gossipsub support
rs-ipfs/rust-ipfs pull request #489
Opened 2021-12-22 15:43 UTC by matthiasbeyer

Hi!

I am new to this project and to the internals of how ipfs works - but I want to use gossipsub and this crate does not yet have support for it, from what I see. So here's my take on implementing it.

Please note that this is a very early draft - so you can stop me from doing anything idiotic before I drown myself in this! :laughing: 

Please tell me if the direction I am heading towards is right - or tell me how to do better!

### Checklist (can be deleted from PR description once items are checked)

- [ ] **New** code is “linted” i.e. code formatting via rustfmt and language idioms via clippy
- [ ] There are no extraneous changes like formatting, line reordering, etc. Keep the patch sizes small!
- [ ] There are functional and/or unit tests written, and they are passing
- [ ] There is suitable documentation. In our case, this means:
    - [ ] Each command has a usage example and API specification
    - [ ] Rustdoc tests are passing on all code-level comments
    - [ ] Differences between Rust’s IPFS implementation and the Go or JS implementations are explained
- [ ] Additions to CHANGELOG.md files

2021-12-22 15:51 UTC, matthiasbeyer commented
No need to approve the workflow run! I just want you to either tell me that I'm writing bullshit here or that the direction is okay and what I should do to make this go into a mergeable direction! :laughing:

2021-12-23 17:42 UTC, koivunej requested changes
It's a nice start, but as mentioned in the comments, just upgrading the current src/p2p/pubsub.rs from floodsub to gossipsub would be the preferred way, hopefully leaving you to do only minimal boilerplate changes.

One issue I can't remember checking with the gossipsub implementation is that are the locally sent messages possible to be echoed in subscriptions. This behaviour at least was expected by the ipfs-interface test suite (the js tests) but it is very much a "cli only" functionality which might not require changes to gossipsub, but would have to be shimmied some other way. However, that's something to worry in the later phases or next PR.

2021-12-23 17:42 UTC, koivunej commented on src/lib.rs
> +    GossipsubSubscribed(OneshotSender<Vec<String>>),
Last I looked, gossipsub is a superset of the floodsub so I think the old entries in IpfsEvent and generally any api just should switch to using gossipsub as the backend. At least it should spare you from writing the boilerplate methods.

2021-12-23 17:42 UTC, koivunej commented on src/p2p/behaviour.rs
> +
This would become unnecessary with the upgrade of pubsub to use gossipsub.

2022-06-14 03:47 UTC, dariusc93 commented
Any update on this? If OP isnt interested I may try to take up on bringing gossip. Still reading over specs, libp2p code but it should be a simple implementation to replace floodsub but is there intentions to keep/use both protocols?

2022-06-14 04:51 UTC, koivunej commented
> Still reading over specs, libp2p code but it should be a simple implementation to replace floodsub but is there intentions to keep/use both protocols?

@dariusc93 No intention to keep both as gossipsub impl in libp2p handles floodsub as well. A simple implementation up to the point of the local echo or that's what I've been assuming, but I haven't checked the gossipsub code in a while.

2022-06-19 15:12 UTC, matthiasbeyer commented
I no longer have time to work on this, sorry. If someone wants to pick this up, feel free to. If not, this can of course be closed.

2022-06-19 15:56 UTC, dariusc93 commented
> I no longer have time to work on this, sorry. If someone wants to pick this up, feel free to. If not, this can of course be closed.

No need to be sorry. Already picked up on this in #507 though still investigating a couple of things (some related to gossipsub and others not so much such as mdns, bootstrap, etc).

2022-09-21 08:01 UTC, closed without merging